{
  "openapi": "3.0.0",
  "info": {
    "title": "DeepDeck Ahuyama API",
    "description": "DeepDeck configuration API",
    "contact": {
      "email": "deepdeck@dsd.dev"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://virtserver.swaggerhub.com/DeepDeckAhuyama/DeepDeck/1.0.0",
      "description": "SwaggerHub API Auto Mocking"
    },
    {
      "url": "http://{DeepDeckIP}",
      "description": "Your DeepDeck (you have to allow unsafe content)",
      "variables": {
        "DeepDeckIP": {
          "description": "IP of DeepDeck",
          "default": "192.168.4.1"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "layers",
      "description": "Operations for Layers"
    },
    {
      "name": "macros",
      "description": "Operations for Macros"
    },
    {
      "name": "tapdance",
      "description": "Operations for Tapdance"
    },
    {
      "name": "modtap",
      "description": "Operations for ModTap"
    }
  ],
  "paths": {
    "/api/layers/layer_names": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Return main information of existing layers",
        "description": "Return an array with the name, position, id, and active flag of the existing layers\n",
        "operationId": "getLAyerNames",
        "responses": {
          "200": {
            "description": "List of layer returned.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LayerDataArray"
                }
              }
            }
          }
        }
      }
    },
    "/api/layers": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Return information of the selected layer",
        "description": "Return the content of the layer\n",
        "operationId": "getLayer",
        "parameters": [
          {
            "name": "uuid",
            "in": "query",
            "description": "The layer ID",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "62d8ba"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Layer returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Layer"
                }
              }
            }
          },
          "400": {
            "description": "Layer not found"
          }
        }
      },
      "put": {
        "tags": [
          "layers"
        ],
        "summary": "Update layer",
        "description": "Update layer\n",
        "operationId": "updateLayer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LayerWithID"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Layer returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Layer"
                }
              }
            }
          },
          "400": {
            "description": "Json not found or not valid"
          }
        }
      },
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Create new layer",
        "description": "Create a new layer\n",
        "operationId": "createLayer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Layer"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Layer returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Layer"
                }
              }
            }
          },
          "400": {
            "description": "Json not found or not valid"
          }
        }
      },
      "delete": {
        "tags": [
          "layers"
        ],
        "summary": "Delete the selected layer",
        "description": "Delete the selected layer\n",
        "operationId": "deleteLayer",
        "parameters": [
          {
            "name": "uuid",
            "in": "query",
            "description": "The layer ID",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "62d8ba"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Layer deleted succesfully"
          },
          "400": {
            "description": "Layer id not found"
          }
        }
      }
    },
    "/api/layers/restore": {
      "put": {
        "tags": [
          "layers"
        ],
        "summary": "Restore default layers",
        "description": "Restore default layers\n",
        "operationId": "restoreLayers",
        "responses": {
          "200": {
            "description": "Layers restored to default"
          }
        }
      }
    },
    "/api/macros": {
      "get": {
        "tags": [
          "macros"
        ],
        "summary": "Return all macros",
        "description": "Return all macros\n",
        "operationId": "getMacros",
        "responses": {
          "200": {
            "description": "Macros returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MacrosList"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "macros"
        ],
        "summary": "Update a macro",
        "description": "Update selected Macro\n",
        "operationId": "updateMacro",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Macros"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Update selected macro"
          }
        }
      },
      "post": {
        "tags": [
          "macros"
        ],
        "summary": "Create new macro.",
        "description": "Create new Macro\n",
        "operationId": "createMacro",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Macros"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Macro created"
          },
          "500": {
            "description": "No more space"
          }
        }
      },
      "delete": {
        "tags": [
          "macros"
        ],
        "summary": "Delete the selected macro",
        "description": "Delete the selected macro\n",
        "operationId": "deleteMacro",
        "parameters": [
          {
            "name": "keycode",
            "in": "query",
            "description": "The macro keycode",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "example": 501
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Macro deleted succesfully"
          },
          "400": {
            "description": "Macro keycode not found"
          }
        }
      }
    },
    "/api/macros/restore": {
      "put": {
        "tags": [
          "macros"
        ],
        "summary": "Restore default macros",
        "description": "Restore default macros\n",
        "operationId": "restoreMacros",
        "responses": {
          "200": {
            "description": "Macros restored to default"
          }
        }
      }
    },
    "/api/tapdance": {
      "get": {
        "tags": [
          "tapdance"
        ],
        "summary": "Return all tapdance",
        "description": "Return all tapdance\n",
        "operationId": "getTapdance",
        "responses": {
          "200": {
            "description": "Tapdance returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TapdanceList"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "tapdance"
        ],
        "summary": "Update a tapdance",
        "description": "Update selected Tapdance\n",
        "operationId": "updateTapdance",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tapdance"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Update selected Tapdance"
          }
        }
      },
      "post": {
        "tags": [
          "tapdance"
        ],
        "summary": "Create new tapdance.",
        "description": "Create new Tapdance\n",
        "operationId": "createTapdance",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tapdance"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Tapdance created"
          },
          "500": {
            "description": "No more space"
          }
        }
      },
      "delete": {
        "tags": [
          "tapdance"
        ],
        "summary": "Delete the selected tapdance",
        "description": "Delete the selected tapdance\n",
        "operationId": "deleteTapdance",
        "parameters": [
          {
            "name": "keycode",
            "in": "query",
            "description": "The tapdance keycode",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "example": 501
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Tapdance deleted succesfully"
          },
          "400": {
            "description": "Tapdance keycode not found"
          }
        }
      }
    },
    "/api/tapdance/restore": {
      "put": {
        "tags": [
          "tapdance"
        ],
        "summary": "Restore default tapdance",
        "description": "Restore default tapdance\n",
        "operationId": "restoreTapdance",
        "responses": {
          "200": {
            "description": "Tapdance restored to default"
          }
        }
      }
    },
    "/api/modtap": {
      "get": {
        "tags": [
          "modtap"
        ],
        "summary": "Return all modtap",
        "description": "Return all modtap\n",
        "operationId": "getModtap",
        "responses": {
          "200": {
            "description": "Modtap returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModtapList"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "modtap"
        ],
        "summary": "Update a modtap",
        "description": "Update selected Modtap\n",
        "operationId": "updateModtap",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Modtap"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Update selected Modtap"
          }
        }
      },
      "post": {
        "tags": [
          "modtap"
        ],
        "summary": "Create new modtap.",
        "description": "Create new Modtap\n",
        "operationId": "createModtap",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Modtap"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Modtap created"
          },
          "500": {
            "description": "No more space"
          }
        }
      },
      "delete": {
        "tags": [
          "modtap"
        ],
        "summary": "Delete the selected modtap",
        "description": "Delete the selected modtap\n",
        "operationId": "deleteModtap",
        "parameters": [
          {
            "name": "keycode",
            "in": "query",
            "description": "The tapdance keycode",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "example": 501
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Modtap deleted succesfully"
          },
          "400": {
            "description": "Modtap keycode not found"
          }
        }
      }
    },
    "/api/modtap/restore": {
      "put": {
        "tags": [
          "modtap"
        ],
        "summary": "Restore default modtap",
        "description": "Restore default modtap\n",
        "operationId": "restoreModtap",
        "responses": {
          "200": {
            "description": "Modtap restored to default"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LayerDataArray": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "example": [
              {
                "name": "Media",
                "pos": 0,
                "active": true,
                "uuid": "62d8ba"
              },
              {
                "name": "Numpad",
                "pos": 1,
                "active": true,
                "uuid": "8531d4"
              },
              {
                "name": "Chrome",
                "pos": 2,
                "active": false,
                "uuid": "17df94"
              }
            ],
            "items": {
              "$ref": "#/components/schemas/LayerInfo"
            }
          }
        }
      },
      "LayerInfo": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Media"
          },
          "pos": {
            "type": "integer",
            "example": 0
          },
          "active": {
            "type": "boolean",
            "example": true
          },
          "uuid": {
            "type": "string",
            "example": "62d8ba"
          }
        }
      },
      "Layer": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Media"
          },
          "active": {
            "type": "boolean"
          },
          "row0": {
            "type": "array",
            "example": [
              {
                "name": "Play",
                "key_code": 171
              },
              {
                "name": "next",
                "key_code": 168
              },
              {
                "name": "mute",
                "key_code": 172
              },
              {
                "name": "layer",
                "key_code": 402
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row0"
            }
          },
          "row1": {
            "type": "array",
            "example": [
              {
                "name": "nWind",
                "key_code": 502
              },
              {
                "name": "PWind",
                "key_code": 503
              },
              {
                "name": "F11",
                "key_code": 68
              },
              {
                "name": "PrtSC",
                "key_code": 70
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row1"
            }
          },
          "row2": {
            "type": "array",
            "example": [
              {
                "name": "Copy",
                "key_code": 500
              },
              {
                "name": "Paste",
                "key_code": 501
              },
              {
                "name": "up",
                "key_code": 82
              },
              {
                "name": "Enter",
                "key_code": 40
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row2"
            }
          },
          "row3": {
            "type": "array",
            "example": [
              {
                "name": "window",
                "key_code": 227
              },
              {
                "name": "left",
                "key_code": 80
              },
              {
                "name": "down",
                "key_code": 81
              },
              {
                "name": "right",
                "key_code": 79
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row3"
            }
          },
          "left_encoder_map": {
            "$ref": "#/components/schemas/Layer_left_encoder_map"
          },
          "right_encoder_map": {
            "$ref": "#/components/schemas/Layer_right_encoder_map"
          },
          "gesture_map": {
            "$ref": "#/components/schemas/Layer_gesture_map"
          }
        }
      },
      "LayerWithID": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Media"
          },
          "active": {
            "type": "boolean"
          },
          "uuid": {
            "type": "string",
            "example": "4e7a48abf8"
          },
          "row0": {
            "type": "array",
            "example": [
              {
                "name": "Play",
                "key_code": 171
              },
              {
                "name": "next",
                "key_code": 168
              },
              {
                "name": "mute",
                "key_code": 172
              },
              {
                "name": "layer",
                "key_code": 402
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row0"
            }
          },
          "row1": {
            "type": "array",
            "example": [
              {
                "name": "nWind",
                "key_code": 502
              },
              {
                "name": "PWind",
                "key_code": 503
              },
              {
                "name": "F11",
                "key_code": 68
              },
              {
                "name": "PrtSC",
                "key_code": 70
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row1"
            }
          },
          "row2": {
            "type": "array",
            "example": [
              {
                "name": "Copy",
                "key_code": 500
              },
              {
                "name": "Paste",
                "key_code": 501
              },
              {
                "name": "up",
                "key_code": 82
              },
              {
                "name": "Enter",
                "key_code": 40
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row2"
            }
          },
          "row3": {
            "type": "array",
            "example": [
              {
                "name": "window",
                "key_code": 227
              },
              {
                "name": "left",
                "key_code": 80
              },
              {
                "name": "down",
                "key_code": 81
              },
              {
                "name": "right",
                "key_code": 79
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Layer_row3"
            }
          },
          "left_encoder_map": {
            "$ref": "#/components/schemas/Layer_left_encoder_map"
          },
          "right_encoder_map": {
            "$ref": "#/components/schemas/Layer_right_encoder_map"
          },
          "gesture_map": {
            "$ref": "#/components/schemas/Layer_gesture_map"
          }
        }
      },
      "Macros": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "keycode": {
            "type": "integer",
            "format": "int16"
          },
          "key": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        },
        "example": {
          "name": "Copy",
          "keycode": 500,
          "key": [
            224,
            6,
            0,
            0,
            0
          ]
        }
      },
      "MacrosList": {
        "type": "object",
        "properties": {
          "macros": {
            "type": "array",
            "example": [
              {
                "name": "Copy",
                "keycode": 500,
                "key": [
                  224,
                  6,
                  0,
                  0,
                  0
                ]
              },
              {
                "name": "Paste",
                "keycode": 501,
                "key": [
                  224,
                  25,
                  0,
                  0,
                  0
                ]
              },
              {
                "name": "AltTab",
                "keycode": 502,
                "key": [
                  226,
                  43,
                  0,
                  0,
                  0
                ]
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Macros"
            }
          }
        }
      },
      "Tapdance": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "tap_list": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "keycode_list": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "keycode": {
            "type": "integer"
          }
        },
        "example": {
          "name": "Media",
          "tap_list": [
            1,
            2,
            3,
            4
          ],
          "keycode_list": [
            171,
            168,
            169,
            172
          ],
          "keycode": 601
        }
      },
      "TapdanceList": {
        "type": "object",
        "properties": {
          "tapdance": {
            "type": "array",
            "example": [
              {
                "name": "Media",
                "tap_list": [
                  1,
                  2,
                  3,
                  4
                ],
                "keycode_list": [
                  171,
                  168,
                  169,
                  172
                ],
                "keycode": 601
              },
              {
                "name": "num",
                "tap_list": [
                  1,
                  3,
                  5,
                  7
                ],
                "keycode_list": [
                  30,
                  32,
                  34,
                  36
                ],
                "keycode": 602
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Tapdance"
            }
          }
        }
      },
      "Modtap": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "keycode_short": {
            "type": "integer"
          },
          "keycode_long": {
            "type": "integer"
          },
          "keycode": {
            "type": "integer"
          }
        },
        "example": {
          "name": "Num12",
          "keycode": 651,
          "keycode_short": 30,
          "keycode_long": 31
        }
      },
      "ModtapList": {
        "type": "object",
        "properties": {
          "tapdance": {
            "type": "array",
            "example": [
              {
                "name": "Num12",
                "keycode": 651,
                "keycode_short": 30,
                "keycode_long": 31
              },
              {
                "name": "Num23",
                "keycode": 652,
                "keycode_short": 32,
                "keycode_long": 33
              }
            ],
            "items": {
              "$ref": "#/components/schemas/Modtap"
            }
          }
        }
      },
      "Layer_row0": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Play"
          },
          "key_code": {
            "type": "integer",
            "format": "int32",
            "example": 171
          }
        }
      },
      "Layer_row1": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "nWind"
          },
          "key_code": {
            "type": "integer",
            "format": "int32",
            "example": 502
          }
        }
      },
      "Layer_row2": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Copy"
          },
          "key_code": {
            "type": "integer",
            "format": "int32",
            "example": 500
          }
        }
      },
      "Layer_row3": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "window"
          },
          "key_code": {
            "type": "integer",
            "format": "int32",
            "example": 227
          }
        }
      },
      "Layer_left_encoder_map": {
        "type": "object",
        "properties": {
          "cw": {
            "type": "integer",
            "format": "int32",
            "example": 174
          },
          "ccw": {
            "type": "integer",
            "format": "int32",
            "example": 173
          },
          "single_press": {
            "type": "integer",
            "format": "int32",
            "example": 171
          },
          "long_press": {
            "type": "integer",
            "format": "int32",
            "example": 172
          },
          "double_press": {
            "type": "integer",
            "format": "int32",
            "example": 168
          }
        }
      },
      "Layer_right_encoder_map": {
        "type": "object",
        "properties": {
          "cw": {
            "type": "integer",
            "format": "int32",
            "example": 505
          },
          "ccw": {
            "type": "integer",
            "format": "int32",
            "example": 504
          },
          "single_press": {
            "type": "integer",
            "format": "int32",
            "example": 506
          },
          "long_press": {
            "type": "integer",
            "format": "int32",
            "example": 509
          },
          "double_press": {
            "type": "integer",
            "format": "int32",
            "example": 508
          }
        }
      },
      "Layer_gesture_map": {
        "type": "object",
        "properties": {
          "up": {
            "type": "integer",
            "format": "int32",
            "example": 174
          },
          "down": {
            "type": "integer",
            "format": "int32",
            "example": 173
          },
          "left": {
            "type": "integer",
            "format": "int32",
            "example": 171
          },
          "right": {
            "type": "integer",
            "format": "int32",
            "example": 172
          },
          "near": {
            "type": "integer",
            "format": "int32",
            "example": 168
          },
          "far": {
            "type": "integer",
            "format": "int32",
            "example": 168
          }
        }
      }
    }
  }
}